### ISSUE TITLE
Simple Library Management

### ISSUE THREAD

**Issue by samipak458** [staticwebdev/30DaysOfSWA#37]
## Requirements
 * Submission ("resource") must have a title, _active_ link and description
 * You must be an author or someone authorized to submit the resource for consideration
 * Submission must be related to Azure Static Web Apps and related technologies
 * Submission adheres to Code of Conduct (no offensive language, non-inclusive narratives)
 * Submission resource can be an article, a project (repo), or an event (meetup or conference)

## Process
 * Fill in the sections below and submit the issue
 * Track issue to know when it gets scheduled - might not always be in the next roundup

---

## Resource Title

**Simple Library Management**

## Resource Link

Repository: [Simple Library Management](https://github.com/samipak458/Simple-Library-Managment)
Website: [Online Library](https://delightful-coast-00b51a700.1.azurestaticapps.net/)

## Resource Description

A simple library management project that is easy to use and helps learners understand the basic concept of JS. You will learn how to implement add, remove/delete, search, and save functionalities & how to deploy, or publish, your website to Azure so that you can show it off to your friends.

## Submitter Name and Github Profile

Muhammad Samiullah (Microsoft Learn Student Ambassador)
GitHub profile: [samipak458](https://github.com/samipak458)

## (Optional) Your Twitter profile

Twitter profile: [samipak458](https://twitter.com/samipak458)

## (Optional) Expiry Date

N/A

**Comment by samipak458** [comment]
@nitya

**Comment by nitya** [comment]
Thanks so much for this @samipak458  - I've tagged it to add to our Sep roundup. Will close issue when that is published, with a link to it. Hugely appreciate this!

**Comment by samipak458** [comment]
Ok ma'am. Thank you for the appreciation 😊

**Comment by samipak458** [comment]
Hello,
@nitya ma'am is it published yet?

**Comment by nitya** [comment]
@samipak458  - apologies I forgot to update the issue and close it!
Yes it was published in the September roundupp
https://www.azurestaticwebapps.dev/blog/roundup-2022-sep 🎉

Thank you so much for the contribution!

cc @saragibby
