### ISSUE TITLE
Wrong URL address in #08: Build A Blog - with Astro

### ISSUE THREAD

**Issue by wenwei-lin** [staticwebdev/30DaysOfSWA#50]
Hi,

I found a wrong URL address in [#08: Build A Blog - with Astro](https://www.azurestaticwebapps.dev/blog/build-with-astro). Under the Astro + SWA heading, the URL for _this template_(tttps://github.com/glaucia86/astro-swa-demo) is wrong. Instead, it should be https://github.com/glaucia86/astro-swa-demo.

Best Regards,
Wenwei

**Comment by nitya** [comment]
Fixed!! Thank you so much - appreciate the heads up!
