### ISSUE TITLE
https://staticwebdev.github.io/30DaysOfSWA/# does not work

### ISSUE THREAD

**Issue by oesolberg** [staticwebdev/30DaysOfSWA#8]
when following the link https://staticwebdev.github.io/30DaysOfSWA/#

the site gives error
Your Docusaurus site did not load properly.

And some of the links on the page does not work (this might be due to docusaurus?)

**Comment by nitya** [comment]
Thank you for the issue! We moved deployment from GitHub Pages to Azure Static Web Apps so I'll make sure we fix all the references to point to the new domain.

**Comment by nitya** [comment]
Todo: Remove GitHub actions workflows, leave only SWA deploymeny

**Comment by nitya** [comment]
Github Actions workflow for GitHub Pages has been disabled.
GitHub Pages settings cleared to remove build from gh-pages branch

Primary deployment will continue to be on Azure Static Web Apps directly.
**GitHub Pages endpoint will not be active at this time**
